"""Add numeric_id to categories-DE2

Revision ID: 046b3add4e04
Revises: ab8255525f4f
Create Date: 2025-03-01 19:56:48.871346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '046b3add4e04'
down_revision: Union[str, None] = 'ab8255525f4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('categories_user_id_fkey', 'categories', type_='foreignkey')
    op.drop_column('categories', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('categories_user_id_fkey', 'categories', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
