"""new coloumn interger id added

Revision ID: 07efb37ad548
Revises: 63ad60012990
Create Date: 2025-02-23 20:42:42.861566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07efb37ad548'
down_revision: Union[str, None] = '63ad60012990'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('integer_id', sa.Integer(), autoincrement=True, nullable=False))
    op.create_unique_constraint(None, 'users', ['integer_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'integer_id')
    # ### end Alembic commands ###
