"""Add numeric_id to categories

Revision ID: 35c0a5320a79
Revises: dbacbe3fde2d
Create Date: 2025-03-01 14:44:42.111937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35c0a5320a79'
down_revision: Union[str, None] = 'dbacbe3fde2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attachments', sa.Column('numeric_id', sa.Integer(), autoincrement=True, nullable=True))
    op.create_index(op.f('ix_attachments_numeric_id'), 'attachments', ['numeric_id'], unique=True)
    op.drop_constraint('categories_numeric_id_key', 'categories', type_='unique')
    op.drop_column('categories', 'numeric_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('numeric_id', sa.INTEGER(), server_default=sa.text("nextval('categories_numeric_id_seq'::regclass)"), autoincrement=True, nullable=False))
    op.create_unique_constraint('categories_numeric_id_key', 'categories', ['numeric_id'])
    op.drop_index(op.f('ix_attachments_numeric_id'), table_name='attachments')
    op.drop_column('attachments', 'numeric_id')
    # ### end Alembic commands ###
