"""Fix ULID issue

Revision ID: 5662dc0e2475
Revises: 5bd8bb1a1436
Create Date: 2025-02-27 14:32:43.101803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5662dc0e2475'
down_revision: Union[str, None] = '5bd8bb1a1436'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
