"""note title column added 

Revision ID: 5bd8bb1a1436
Revises: e5be0050ce5c
Create Date: 2025-02-27 14:29:27.391665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bd8bb1a1436'
down_revision: Union[str, None] = 'e5be0050ce5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('title', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notes', 'title')
    # ### end Alembic commands ###
