"""lastname can be null

Revision ID: 5c0d2bd4aff1
Revises: 910645689919
Create Date: 2025-02-23 23:11:46.641701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c0d2bd4aff1'
down_revision: Union[str, None] = '910645689919'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
     # Ensure no NULL values before altering the column
    op.alter_column('users', 'integer_id',
                existing_type=sa.INTEGER(),
                nullable=False,
                autoincrement=True)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'last_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('users', 'integer_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    # ### end Alembic commands ###
