"""Add numeric_id to categories

Revision ID: 7396950902d7
Revises: 35c0a5320a79
Create Date: 2025-03-01 14:49:30.976569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7396950902d7'
down_revision: Union[str, None] = '35c0a5320a79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('numeric_id', sa.Integer(), autoincrement=True, nullable=True))
    op.create_index(op.f('ix_categories_numeric_id'), 'categories', ['numeric_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_categories_numeric_id'), table_name='categories')
    op.drop_column('categories', 'numeric_id')
    # ### end Alembic commands ###
