"""Fix password field and timestamps

Revision ID: 847c0bc57db2
Revises: e7a1e11dc54f
Create Date: 2025-02-22 20:18:24.370027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '847c0bc57db2'
down_revision: Union[str, None] = 'e7a1e11dc54f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
