"""Fix numeric_id sequence for categories

Revision ID: a693a2d4e23d
Revises: c31a726d0faa
Create Date: 2025-03-01 20:12:16.096998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a693a2d4e23d'
down_revision: Union[str, None] = 'c31a726d0faa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('categories', 'numeric_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('categories', 'numeric_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
