"""Add user_id to categories

Revision ID: c31a726d0faa
Revises: 046b3add4e04
Create Date: 2025-03-01 20:04:31.536329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c31a726d0faa'
down_revision: Union[str, None] = '046b3add4e04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('user_id', sa.Integer(), nullable=True))
    op.alter_column('categories', 'numeric_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'categories', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'categories', type_='foreignkey')
    op.alter_column('categories', 'numeric_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('categories', 'user_id')
    # ### end Alembic commands ###
