"""Updated primary key and added user_ulid

Revision ID: c8839f4725b6
Revises: 8fe7b8f03283
Create Date: 2025-02-24 00:20:48.469942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8839f4725b6'
down_revision: Union[str, None] = '8fe7b8f03283'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_integer_id_key', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('users_integer_id_key', 'users', ['id'])
    # ### end Alembic commands ###
