"""Added notes, categories, and attachments tables small change 

Revision ID: e5be0050ce5c
Revises: 2272d0d50f5f
Create Date: 2025-02-27 11:17:31.566265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5be0050ce5c'
down_revision: Union[str, None] = '2272d0d50f5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
