"""Add default to date column

Revision ID: f2d6e1fffcca
Revises: 6d0482985acf
Create Date: 2025-02-27 15:05:09.174549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2d6e1fffcca'
down_revision: Union[str, None] = '6d0482985acf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('date', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notes', 'date')
    # ### end Alembic commands ###
