"""Add default to date column

Revision ID: f34b7d9abbf8
Revises: f2d6e1fffcca
Create Date: 2025-02-27 15:17:43.043591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f34b7d9abbf8'
down_revision: Union[str, None] = 'f2d6e1fffcca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attachments', 'date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attachments', sa.Column('date', sa.DATE(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
