"""Add subscription tables

Revision ID: f5f8051a9b3e
Revises: 194cfe3cc29a
Create Date: 2025-03-15 19:22:56.700383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5f8051a9b3e'
down_revision: Union[str, None] = '194cfe3cc29a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_category_name', table_name='categories')
    op.drop_index('idx_category_user', table_name='categories')
    op.drop_index('idx_note_category', table_name='notes')
    op.drop_index('idx_note_created', table_name='notes')
    op.drop_index('idx_note_user', table_name='notes')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_note_user', 'notes', ['user_id'], unique=False)
    op.create_index('idx_note_created', 'notes', ['created_at'], unique=False)
    op.create_index('idx_note_category', 'notes', ['category_id'], unique=False)
    op.create_index('idx_category_user', 'categories', ['user_id'], unique=False)
    op.create_index('idx_category_name', 'categories', ['name'], unique=False)
    # ### end Alembic commands ###
