"""Change id to ULID

Revision ID: fe1788eb3490
Revises: b1c350920a2c
Create Date: 2025-02-23 19:20:02.437610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe1788eb3490'
down_revision: Union[str, None] = 'b1c350920a2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=26),
               existing_nullable=False)
    op.drop_index('ix_users_id', table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    op.alter_column('users', 'id',
               existing_type=sa.String(length=26),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
