name: Deploy to AWS ECR and Lambda

on:
  push:
    branches:
      - master
  workflow_dispatch:    

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      ECR_PUBLIC_REGISTRY: public.ecr.aws/r5p8n8t0/cloudnotes
      IMAGE_TAG: latest
      AWS_LAMBDA_REGION: ${{ secrets.AWS_REGION }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR Public
        run: |
          aws ecr-public get-login-password --region us-east-1 | \
          docker login --username AWS --password-stdin public.ecr.aws

      - name: Build, Tag, and Push Docker Image        
        run: |
          docker build -t cloudnotes-lambda .
          docker tag cloudnotes-lambda:latest public.ecr.aws/r5p8n8t0/cloudnotes:latest
          docker push public.ecr.aws/r5p8n8t0/cloudnotes:latest

          
      - name: Update Lambda Function in ap-south-2
        run: |
            aws lambda update-function-code \
              --region ap-south-2 \
              --function-name cloudnotes-fastapi \
              --image-uri public.ecr.aws/r5p8n8t0/cloudnotes:latest

