name: Deploy to AWS ECR and Lambda

on:
  push:
    branches:
      - master
  workflow_dispatch:    

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      ECR_PUBLIC_REGISTRY: public.ecr.aws/r5p8n8t0/ramaeondev
      IMAGE_TAG: latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR Public
        run: |
          aws ecr-public get-login-password --region us-east-1 | \
          docker login --username AWS --password-stdin public.ecr.aws

      - name: Build, Tag, and Push Docker Image        
        run: |
            docker build --no-cache -t logit .
            docker tag logit $ECR_PUBLIC_REGISTRY/logit:$IMAGE_TAG
            docker push $ECR_PUBLIC_REGISTRY/logit:$IMAGE_TAG
          
      # - name: Update Lambda Function
      #   run: |
      #       aws lambda update-function-code \
      #       --function-name cloudnotes-fastapi \
      #       --image-uri $ECR_PUBLIC_REGISTRY/logit:$IMAGE_TAG
